import Head from "next/head";
import { useEffect } from "react";
import { useAppState } from "../../lib/state";

export default function Track({ children }) {
  //   const { setChordbooks, clearTrackData } = useAppState();
  //   useEffect(() => {
  //     return () => {
  //       setChordbooks([]);
  //       clearTrackData();
  //     };
  //   }, []);
  return (
    <div>
      <Head>
        <title>Music Matters - Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Track</h1>
        {children}
      </main>
    </div>
  );
}
